PRODUTOS_SINTEGRE = [
    "Relatório de Acompanhamento Hidrológico",
    "Modelo GEFS",
    "Resultados preliminares não consistidos (vazões semanais - PMO)",
    "Relatório dos resultados finais consistidos da previsão diária (PDP)",
    "Níveis de Partida para o DESSEM",
    "DADVAZ – Arquivo de Previsão de Vazões Diárias (PDP)",
    "Deck e Resultados DECOMP - Valor Esperado",
    "Resultados finais consistidos (vazões diárias - PDP)",
    "Resultados preliminares consistidos (vazões semanais - PMO)",
    "Arquivos dos modelos de previsão de vazões semanais - PMO",
    "Arquivos dos modelos de previsão de vazões diárias - PDP",
    "Acomph",
    "RDH",
    "Histórico de Precipitação por Satélite - ONS",
    "Modelo ETA",
    "Deck Preliminar DECOMP - Valor Esperado",
    "Decks de entrada e saída - Modelo DESSEM",
    "Arquivos de Previsão de Carga para o DESSEM",
    "Decks de entrada do PrevCargaDESSEM",
    "Previsões de carga mensal e por patamar - NEWAVE",
    "IPDO (Informativo Preliminar Diário da Operação)",
    "Modelo ECMWF",
    "Dados utilizados na previsão de geração eólica",
    "Arquivos de Previsão de Carga para o DESSEM - PrevCargaDESSEM",
    "DECKS DA PREVISÃO DE GERAÇÃO EÓLICA SEMANAL WEOL-SM",
    "Preliminar - Relatório Mensal de Limites de Intercâmbio",
    "Carga por patamar - DECOMP",
    "Relatório Mensal de Limites de Intercâmbio para o Modelo DECOMP",
    "Notas Técnicas - Medio Prazo",
    "Deck NEWAVE Preliminar",
    "DECK NEWAVE DEFINITIVO",
    "Decks de entrada e saída do processo sombra - Modelo GEVAZP"
]